### ISSUE TITLE
KMH

### ISSUE THREAD

**Issue by Frans29** [IllusiveTea/FiveM-RichPresence#2]
How can i set it to kmh?

**Comment by cooljddj** [comment]
Seeing how owner seems inactive check this out if you still need https://github.com/cooljddj/FiveM-RichPresence

**Comment by logan-mcgee** [comment]
weird method of doing it, wouldve been nicer to have some sort of toggle in a config or convar.

**Comment by logan-mcgee** [comment]
added an update which uses the convar `RichUseKMH` to switch from measuring speeds to KPH
